version: '3.8'
services:
  service-registry:
    build:
      context: .
      dockerfile: service-registry/Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - service-registry

  backend-bank-system:
    build:
      context: .
      dockerfile: backend-bank-system/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry

  ledger-service:
    build:
      context: .
      dockerfile: ledger-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry

# Añade más servicios según sea necesario