server:
  port: 8085

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: orchestrator_route
          uri: lb://orchestrator
          predicates:
            - Path=/api/v1/transfer/**
        - id: backend_route
          uri: lb://backend-bank-system
          predicates:
            - Path=/api/v1/accounts/**
