spring:
  application:
    name: backend-bank-system
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankdb}
    username: ${SPRING_DATASOURCE_USERNAME:bank}
    password: ${SPRING_DATASOURCE_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework: INFO

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  outbox:
    topic: ${KAFKA_OUTBOX_TOPIC:dbserver1.bankdb.public.outbox}
  account:
    events:
      topic: ${KAFKA_ACCOUNT_EVENTS_TOPIC:account.events}
  dlq:
    topic: ${KAFKA_DLQ_TOPIC:account.events.dlq}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

camel:
  springboot:
    name: backend-bank-system
